In [2]:
import torch
import numpy as np

In [3]:
arr= np.array([1,2,3,4,5])

In [6]:
x=torch.from_numpy(arr)

In [5]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [7]:
arr2d= np.arange(0.0,12.0).reshape(4,3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [8]:
x2=torch.from_numpy(arr2d)

In [9]:
my_arr= np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
my_tensor= torch.tensor(my_arr)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

### Note

`torch.from_numpy` and `torch.as_tensor` maintains a relationship with the original numpy array and if it's changed tensor changes too.

Thus `torch.tensor()` used to avoid linking tensor array to original array

`torch.tensor()` retains the data type of the passed in arrays whereas `torch.Tensor()` converts the dtype to Float

## Creating Tensors from scratch in PyTorch

#### Creating an empty tensor

In [12]:
torch.empty(4,2)

tensor([[0.0000e+00, 0.0000e+00],
        [2.6310e+20, 8.2649e+20],
        [4.2484e-05, 3.4005e-06],
        [6.5264e-10, 2.6701e-06]])

In [14]:
torch.zeros(4,3,dtype= torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [15]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
torch.arange(0,20,2).reshape(2,5)

tensor([[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]])

In [20]:
my_tensor=torch.tensor([1,2,3,4])

In [22]:
my_tensor.dtype

torch.int64

In [24]:
my_tensor=my_tensor.type(torch.int32)

In [25]:
my_tensor.dtype

torch.int32

In [26]:
torch.rand(4,3)

tensor([[0.7442, 0.1495, 0.1304],
        [0.9082, 0.8924, 0.0474],
        [0.6993, 0.1010, 0.5463],
        [0.6920, 0.8642, 0.7711]])

In [27]:
torch.randn(4,5)

tensor([[-0.6604, -0.1769, -0.3790, -0.3035, -0.7555],
        [ 3.0096,  1.7696, -0.9424,  1.0746,  1.1784],
        [-0.8415, -0.7611, -0.3700,  0.6785, -1.3151],
        [-0.6838, -0.2502,  0.8129,  0.1801,  2.7353]])

In [28]:
torch.randint(low=0,high=20,size=(4,4))

tensor([[15, 18, 17, 12],
        [13, 16,  5,  5],
        [ 7, 19, 19,  8],
        [ 5,  9,  8, 15]])

### Creating tensors of specific input size

In [30]:
x=torch.zeros(2,5)

y=torch.rand_like(x)
y

tensor([[0.3242, 0.0180, 0.9032, 0.6379, 0.4406],
        [0.2904, 0.8249, 0.9668, 0.9047, 0.2477]])

## Random seed initialization

In [31]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])